CREATE TABLE IF NOT EXISTS `VisitorProfile` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `visitor_uuid` CHAR(36) NOT NULL,
  `institution` VARCHAR(255) NOT NULL,
  `lab_name` VARCHAR(255) NOT NULL,
  `person_name` VARCHAR(255) NOT NULL,
  `cookie_key` VARCHAR(128) DEFAULT NULL,
  `visit_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `first_seen_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `last_seen_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `last_path` VARCHAR(255) DEFAULT NULL,
  `last_ip` VARCHAR(45) DEFAULT NULL,
  `last_user_agent` VARCHAR(512) DEFAULT NULL,
  `created_by_user_id` INT DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_visitorprofile_uuid` (`visitor_uuid`),
  UNIQUE KEY `uniq_visitorprofile_cookie_key` (`cookie_key`),
  KEY `idx_visitorprofile_name` (`person_name`),
  KEY `idx_visitorprofile_institution_lab` (`institution`, `lab_name`),
  KEY `idx_visitorprofile_last_seen_at` (`last_seen_at`),
  KEY `idx_visitorprofile_created_by_user_id` (`created_by_user_id`),
  CONSTRAINT `fk_visitorprofile_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `customuser` (`uid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `VisitorAccessLog` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `visitor_id` BIGINT NOT NULL,
  `visited_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `path` VARCHAR(255) NOT NULL,
  `method` VARCHAR(16) NOT NULL DEFAULT 'GET',
  `ip` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(512) DEFAULT NULL,
  `referer` VARCHAR(512) DEFAULT NULL,
  `cookie_snapshot` JSON DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_visitoraccesslog_visitor_id` (`visitor_id`),
  KEY `idx_visitoraccesslog_visited_at` (`visited_at`),
  KEY `idx_visitoraccesslog_path` (`path`),
  CONSTRAINT `fk_visitoraccesslog_visitor` FOREIGN KEY (`visitor_id`) REFERENCES `VisitorProfile` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
